### ISSUE TITLE
Add bee (command line tool) to Backdrop recipe

### ISSUE THREAD

**Issue by yorkshire-pudding** [lando/backdrop#13]
Bee is a command line tool built specially for Backdrop but influenced by Drush.  Given that Drush for Backdrop is dependent on Drush 8 which will not be supported once Drupal 7 reaches end of life, we are keen to encourage wider adoption (and development) of bee to ensure that a supported solution is available going forward.

While we have [this in our wiki](https://github.com/backdrop-contrib/bee/wiki/Using-Bee-with-Lando), it would be good to include bee by default in the backdrop recipe.  I've had a look at the code for this project, but not sure where this config would go.

This is what is in the guidance:
Add some build steps that download and install Bee:
services:

```yml
  appserver:
    build:
      - wget -qO bee.zip https://github.com/backdrop-contrib/bee/archive/1.x-1.x.zip
      - unzip -q bee.zip && rm bee.zip
      - mv bee-1.x-1.x /usr/local/bin/bee
 ```

Add a tooling command for bee:

```yml
tooling:
  bee:
    service: appserver
    cmd: /usr/local/bin/bee/bee.php
```

I tend to change the last line to be:

```yml
cmd: /usr/local/bin/bee/bee.php --root=/app/docroot
```

I set `docroot` to be the `webroot` in the recipe.  I don't know if it's possible to derive the `webroot` setting in the tooling command for the recipe?  That is a nice to have rather than essential
i.e. 

```yml
cmd: /usr/local/bin/bee/bee.php --root=/app/${webroot}
```
